[package]
name = "archroom-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
archroom-core = { workspace = true }
egui = "0.33"
egui_extras = { version = "0.33", features = ["image"] }
serde = { workspace = true }

[dev-dependencies]
egui_kittest = "0.33"
