//! Raw FFI bindings to the system LibRaw, generated by `bindgen` in `build.rs`.
//! Kept deliberately thin: `archroom-io` provides the safe wrapper.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(missing_debug_implementations)]
// The rest of this file is bindgen output, not code we wrote; it doesn't
// owe our style lints an explanation.
#![allow(clippy::all, clippy::pedantic, clippy::missing_safety_doc)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
